### PR TITLE
Add more bv rewrites

### PR DESCRIPTION
**Pull request by anishathalye**
This patch adds the following bitvector-related rewrites:

- Add bv extract / extract rewrite
- Generalize bv extract / {sign,zero}-extend rewrite

Before this patch, extract / {sign,zero}-extend was only simplified if we were extracting out exactly the argument of the {sign,zero}-extend. However, we can simplify this for any `(extract i 0 _)` while introducing at most as many new terms as we did before.

One practical example that prompted me to add the former is:

```racket
(extract 0 0 (extract 9 1 (concat (bv #b1 1) (concat (extract 7 0 x) (bv #b0 1)))))
```

Without the patch, this isn't simplified, but with the extract / extract rewrite, it's simplified to:

```racket
(extract 0 0 x)
```

### CODE REVIEW

**Comment by anishathalye** [comment]
Also, by the way, this PR is failing the tests on some Racket versions because of an issue with HTTPS certificates. When testing with `RACKET_VERSION=7.0`, `install-racket.sh` [downloads](https://github.com/greghendershott/travis-racket/blob/master/install-racket.sh#L47) from <https://www.cs.utah.edu/plt/installers/7.0/racket-7.0-x86_64-linux.sh>. That site is serving a certificate chain that includes the [recently expired](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020) Sectigo AddTrust External CA Root, so the download fails.

If you switch to `os: bionic` in the `.travis.yml`, it fixes this problem (because I think the intermediate CA, USERTrust RSA Certification Authority, is trusted there). Alternatively, doing something like `apt-get --only-upgrade install ca-certificates` on the current (default) xenial before running `install-racket.sh` fixes it as well.

**Comment by emina** [comment]
Yeah, we noticed the failure and were looking for a fix.  Let me try the one you suggest!

**Comment by anishathalye** [comment]
I've gone with the former in one of my projects ([ref](https://github.com/anishathalye/rtl/commit/78b4eae1a6614d8a95f30375c8ecc82321c8c091)), and it seems to work fine (and I prefer testing on 18.04 over 16.04 anyways).

**Comment by emina** [comment]
All done, thanks!

**Pull request merged**
