### PR TITLE
Add logical xor operation

### PR DESCRIPTION
**Pull request by whitequark**
I was working on a boolean function minimizer that would have support for xor terms, and thought it would be handy to have logical XOR operations. Let me know if this is useful.

### CODE REVIEW

**Comment by sorawee** [comment]
FWIW, there's `xor` already in Rosette: https://github.com/emina/rosette/blob/master/rosette/base/form/control.rkt#L84

**Comment by whitequark** [comment]
Right, but there's both `and` and `&&`.

**Comment by whitequark** [comment]
By the way, here's the logic minimizer: https://gist.github.com/whitequark/e4e559f6316beb026c87d58f4413a157. Rosette is so awesome.

**Comment by emina** [comment]
Adding a new operator to Rosette's IR involves several changes in addition to the ones in these files.  For example, it's also necessary to add a translation from the new operator to SMT, otherwise queries that use that operator will fail:

```
#lang rosette

(define-symbolic a b boolean?)

(solve
 (assert (^^ a b)))

Error: ../../Applications/Racket v7.4/collects/racket/private/kw.rkt:1360:47: enc: cannot encode (^^ a b) to SMT
```

In general, tools like Rosette will choose a small set of core boolean operators, and reduce everything to that small core set.  Rosette chooses negation, conjunction, and disjunction. This allows it use fewer rewrite rules and (heuristically) catch more opportunities for detecting equivalences, which is important for effective partial evaluation (i.e., eliminating as many dead/false branches upfront).

A quick note on the [logic minimizer code](https://gist.github.com/whitequark/e4e559f6316beb026c87d58f4413a157): using predicates such as `(? boolean?)` in `match` statements won't do the right thing.  Rosette's `match` can deconstruct structures, lists, etc., but everything inside a pattern must be a pattern variable.  So `(list a b c)` will work correctly and so will just `a`, where these are pattern variables, but something like `(list (? boolean?))` or just `(? boolean?)` will not.  Rosette's `match` is much more limited than Racket's (and that's why it's not currently documented / encouraged for general use). To get around this limitation, consider modifying `lcost` as follows:

```
(define (lcost e)
  (match e
    [(lnot a)   (+ 1 (lcost a))]
    [(land a b) (+ 2 (lcost a) (lcost b))]
    [(lor  a b) (+ 2 (lcost a) (lcost b))]
    [(lxor a b) (+ 2 (lcost a) (lcost b))]
    [_ 1]))
```

**Comment by whitequark** [comment]
> Adding a new operator to Rosette's IR involves several changes in addition to the ones in these files.

Gotcha, thanks. I was thinking it's probably not going to be so easy.

> Rosette's `match` is much more limited than Racket's (and that's why it's not currently documented / encouraged for general use).

Ah, I was wondering about it. I understood some of its other limitations but not this one.

> To get around this limitation, consider modifying `lcost` as follows:

Unfortunately this doesn't capture my intent (but neither does my code, clearly). What I wanted is to make literals (like `#t`) cost more than universally quantified symbolic constants (like `a`). Although it turned out that in my end application, a unit cost function works just fine, I'm still curious if I can do that; can you suggest a solution here?

**Comment by emina** [comment]
Ah, yes, I'd suggest doing something like this:

```
#lang rosette/safe
(require rosette/lib/angelic
         rosette/lib/match)

(define (^^ x y) (|| (&& x (! y)) (&& (! x) y)))

(struct lnot (a)   #:transparent)
(struct land (a b) #:transparent)
(struct lor  (a b) #:transparent)
(struct lxor (a b) #:transparent)
(struct lvar (v)   #:transparent)
(struct lit  (v)   #:transparent)

(define (ldump e)
  (match e
    [(lnot a)   `(! ,(ldump a))]
    [(land a b) `(&& ,(ldump a) ,(ldump b))]
    [(lor  a b) `(\|\| ,(ldump a) ,(ldump b))]
    [(lxor a b) `(^^ ,(ldump a) ,(ldump b))]
    [(lvar v)    v]
    [(lit  v)    v]))

(define (leval e)
  (match e
    [(lnot a)   (!  (leval a))]
    [(land a b) (&& (leval a) (leval b))]
    [(lor  a b) (|| (leval a) (leval b))]
    [(lxor a b) (^^ (leval a) (leval b))]
    [(lvar v)   v]
    [(lit  v)   v]))

(define (lcost e)
  (match e
    [(lnot a)   (+ 1 (lcost a))]
    [(land a b) (+ 2 (lcost a) (lcost b))]
    [(lor  a b) (+ 2 (lcost a) (lcost b))]
    [(lxor a b) (+ 2 (lcost a) (lcost b))]
    [(lit  v)   1]
    [(lvar v)   0]))

(define (??lexpr terminals #:depth depth)
  (apply choose*
    (if (<= depth 0) terminals
    (let [(a (??lexpr terminals #:depth (- depth 1)))
          (b (??lexpr terminals #:depth (- depth 1)))]
      (append terminals
        (list (lnot a) (land a b) (lor a b) (lxor a b)))))))

(define (lmincost #:forall inputs #:tactic template #:equiv behavior)
  (define model
    (optimize
      #:minimize  (list (lcost template))
      #:guarantee (assert (forall inputs (equal? (leval template) behavior)))))
  (if (unsat? model) model
      (evaluate template model)))

(define-symbolic a b c boolean?)
(define f
  (lmincost
    #:forall (list a b c)
    #:tactic (??lexpr (list (lvar a) (lvar b) (lvar c) (lit #t) (lit #f)) #:depth 3)
    #:equiv  (&& (|| a (! (&& b c))) (! (&& a (|| (! b) (! c)))))))
(displayln (ldump f)) ; (! (^^ (&& c b) a))
```

**Comment by whitequark** [comment]
Makes sense, thank you. I thought of this solution but I was wondering if there was something simpler. It works fine though.

**Comment by emina** [comment]
There is something simpler, but I'd still suggest going with this solution because it gives you full control over the circuit language and fewer surprises if you plan to extend it.

The simpler one involves changing `lcost` as follows:

```
(define (lcost e)
  (match e
    [(lnot a)   (+ 1 (lcost a))]
    [(land a b) (+ 2 (lcost a) (lcost b))]
    [(lor  a b) (+ 2 (lcost a) (lcost b))]
    [(lxor a b) (+ 2 (lcost a) (lcost b))]
    [_ (if (constant? e) 0 1)])) 
```

The procedure `constant?` returns `#t` only for symbolic constants, so in this example:

```
> (constant? a)
#t
> (constant? (&& a b))
#f
> (constant? #t)
#f
> (constant? #f)
#f
```

**Pull request closed without merging**
