### PR TITLE
Package

### PR DESCRIPTION
**Pull request by LeifAndersen**

### CODE REVIEW

**Comment by bennn** [comment]
Adds info files to make Rosette work as a package. On this branch you should be able to get a working copy of Rosette by running:

```
    > git clone ... rosette
    > raco pkg install ./rosette     # The ./ is important
```

(Once rosette is on http://pkgs.racket-lang.org/, install will just be `raco pkg install rosette`)


The fun part is installing z3 during setup. If the user doesn't have a `bin/z3` directory, we download & unpack a z3 binary. That code starts [here](https://github.com/emina/rosette/pull/15/files#diff-f3bb56ec9799d80575e2f07f4e891b36R3).

FYI, if the docs were under the `rosette` folder, I'm pretty sure we'd only need 1 `info.rkt` file. (Like this [info.rkt](https://github.com/bennn/glob/blob/master/info.rkt), for example).

**Comment by emina** [comment]
Awesome!  You guys are fast! :)  A few quick questions and comments are below.

* Do you know why CI is failing?  Is the package system interacting somehow with `raco setup`, which is what we use in .travis.yml to build Rosette for testing?  How do we need to change .travis.yml with the new packaging in place?

* Rosette 2.0 uses the latest (not yet released) version of Z3 (4.4.2).  I am personally using Z3 commit d89c39cbe2bb862daff2c183a79361360f7e2dc1.

* Should doc/guide be moved into the rosette source folder?  Ben's comment seems to suggest that this would simplify packaging.

**Comment by jamesbornholt** [comment]
This patch is awesome!

CI failed because the script checks `(directory-exists? "z3")` when on Travis, `bin/z3` is the executable itself. I think instead of nesting the z3 download in `bin/z3/bin/z3`, we should download the z3 distribution to `z3/` in the root (or someplace else if there's an idiomatic place for this), and then symlink `bin/z3` to that distribution if that file doesn't already exist. That way it's easy to replace z3 with our own build (which we do often). This would also require undoing the change to `z3.rkt`.

**Comment by LeifAndersen** [comment]
Yup, we thought about that. The reason I didn't go for that is because not all platforms treat symlinks the same.

Namely, if you want this package to work out of the box on Windows, you'll have to do something different because it doesn't have the same notion of symlinks as Linux/OSX (IIRC anyway).

Also, it's probably a good idea to do better error checking so that the user gets cleaner errors if something goes wrong. Errors 'should' get caught at the moment (crosses fingers), but nice messages aren't yet printed out.

**Comment by bennn** [comment]
- Thanks @jamesbornholt  :) I guess for now we could download to `(find-system-path 'collects-dir)` [docs](http://docs.racket-lang.org/reference/Filesystem.html)
- Sounds like we should wait to merge this until 4.4.2 is released
- Unless you want the guide folder at the top for other things, I do think we should move it.

**Comment by bennn** [comment]
> I guess for now we could download to (find-system-path 'collects-dir)

Oops I misunderstood. The root of the rosette package sounds good. Also we'll update this PR to get the right z3 commit for now.

**Comment by emina** [comment]
That would be fantastic!  Thank you!

I will merge the package (with the new Z3) once we figure out how to get this working with CI.

I have pushed a change to the refactor-ops branch that moves doc into rosette/.

**Pull request closed without merging**
